include: package:flutter_lints/flutter.yaml

analyzer:
    exclude:
        - "lib/**/*.g.dart"
        - "lib/**/*.freezed.dart"
    plugins:
        - custom_lint
    errors:
        invalid_annotation_target: ignore

linter:
    rules:
        avoid_print: true
        prefer_single_quotes: true
        constant_identifier_names: false
        non_constant_identifier_names: false
        sort_child_properties_last: false
        avoid_renaming_method_parameters: false
        no_leading_underscores_for_local_identifiers: false
        avoid_manual_providers_as_generated_provider_dependency: false
#        prefer_const_constructors: false
