name: flutter_app
description: Flutter boilerplate.
publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=3.1.5 <4.0.0"
    flutter: ">=3.0.0"

dependencies:
    flutter:
        sdk: flutter

    http: ^1.1.0
    mime: ^1.0.4

    intl: ^0.19.0
    url_launcher: ^6.2.2
    file_picker: ^6.1.1
    shared_preferences: ^2.2.2
    share_plus: ^7.2.1
    webview_flutter: ^4.4.2
    camera: ^0.10.5+5
    go_router: ^12.1.1
    path_provider: ^2.1.1
    video_player: ^2.8.1

    google_sign_in: ^6.1.5
    sign_in_with_apple: ^5.0.0

    google_fonts: ^6.1.0
    cupertino_icons: ^1.0.2

    flutter_svg: ^2.0.9

    hooks_riverpod: ^2.4.9
    flutter_hooks: ^0.20.3
    riverpod_annotation: ^2.3.3
    freezed_annotation: ^2.4.1
    json_annotation: ^4.8.1

    firebase_core: ^2.24.0 # https://firebase.flutter.dev/docs/overview
    firebase_crashlytics: ^3.4.5
    firebase_analytics: ^10.7.1
    firebase_messaging: ^14.7.5
    firebase_dynamic_links: ^5.4.8

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^2.0.0

    flutter_launcher_icons: "^0.13.1"

    build_runner: ^2.4.7
    source_gen: ^1.4.0

    #go_router_builder: ^2.4.0

    riverpod_generator: ^2.3.9
    custom_lint: ^0.5.7
    riverpod_lint: ^2.3.7
    freezed: ^2.4.5
    json_serializable: ^6.7.1

flutter:
    uses-material-design: true
    assets:
        - assets/icons/
        - assets/images/

# flutter pub run flutter_launcher_icons
flutter_launcher_icons:
    android: true
    ios: true
    image_path: "assets/images/launcher.png"
    min_sdk_android: 21
