// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVnuY9B3y5xxTEXxjUIwEZHbbG1iBev7I',
    appId: '1:122498097411:web:95d57b56c9233af30d4936',
    messagingSenderId: '122498097411',
    projectId: 'v-connect-app',
    authDomain: 'v-connect-app.firebaseapp.com',
    storageBucket: 'v-connect-app.appspot.com',
    measurementId: 'G-3NGE3GDN5R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHVOmGBFEFpRoToWwZ9eddpQBoE0gyqmo',
    appId: '1:122498097411:android:256624dd03ae3a620d4936',
    messagingSenderId: '122498097411',
    projectId: 'v-connect-app',
    storageBucket: 'v-connect-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlRY7okkhghx6D95h9YwA-QHlRt9hP2P4',
    appId: '1:122498097411:ios:e448fc65667f665d0d4936',
    messagingSenderId: '122498097411',
    projectId: 'v-connect-app',
    storageBucket: 'v-connect-app.appspot.com',
    androidClientId: '122498097411-24odv4kcpd2shlrbolpsh5ed0qatavgr.apps.googleusercontent.com',
    iosClientId: '122498097411-dijqcplope9csfo0mo2qt4ab5j3ttkf8.apps.googleusercontent.com',
    iosBundleId: 'app.vsolution.flutter_app',
  );
}
